### ISSUE TITLE
After compilation canvas not working

### ISSUE THREAD

**Issue by cmsnerd** [greut/pianotune#1]
Hello, after installation with yarn,i get compiled .js file in dist, but opening index file gives me only static canvas, could you ,please descripe what else do i need include to make it work,like in your video on youtube?
I'm looking for a way to draw .json files on canvas, and only that,no playing sounds,or other stuff, cant find anything similar to this but your yt video ;/

**Comment by cmsnerd** [comment]
Do i really need tune.js or other libraries to make pianotune works? Should i import jQuery in index footer?

**Comment by greut** [comment]
things are probably outdated, follow the README.
